# Generated by Django 4.2.3 on 2023-08-13 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=50)),
                ('estado_de_documentacion', models.CharField(max_length=50)),
                ('financiacion', models.CharField(max_length=50)),
                ('proximo_paso', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Nuevos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('combustible', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=0, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=50)),
                ('turnos', models.DateField(max_length=50)),
                ('mantenimiento', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('kilometraje', models.PositiveBigIntegerField()),
                ('precio', models.DecimalField(decimal_places=0, max_digits=20)),
            ],
        ),
    ]
